name: Test

on: [push, workflow_dispatch]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # Set up Node.js environment
      - uses: actions/setup-node@v3
        with:
          node-version: 19
          cache: npm

      # Create a package-lock.json if it doesn't exist
      - name: Ensure package-lock.json exists
        run: |
          if [ ! -f package-lock.json ]; then
            echo "{}" > package.json
            npm install --package-lock-only
          fi

      # Install your project packages & dependencies
      - name: Install Node.js dependencies
        run: npm install

      # Install Testmo CLI tool locally (then use npx testmo .. to run it)
      - run: npm install --no-save @testmo/testmo-cli


      # Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Python dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt

      # Run automated tests and report results to Testmo
      - run: |
          source venv/bin/activate
          pytest --junitxml=results/results.xml
          npx testmo automation:run:submit \
            --instance "$TESTMO_URL" \
            --project-id 1 \
            --name "Test run" \
            --source "github-action" \
            --results results/results.xml
        env:
          TESTMO_URL: ${{ secrets.TESTMO_URL }}
          TESTMO_TOKEN: ${{ secrets.TESTMO_TOKEN }}
